# Generated by Django 5.0.14 on 2025-07-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
