# Generated by Django 5.0.14
from django.db import migrations
from django.contrib.auth.models import UserManager

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', UserManager()),
            ],
        ),
    ]