# Generated by Django 5.0.14 on 2025-07-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fix_user_manager'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
