# Generated by Django 5.0.14 on 2025-07-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_auth_source'),
        ('api', '0007_add_is_active_to_event'),
    ]

    operations = [
    ]
