# Generated by Django 5.0.14 on 2025-07-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_auth_source'),
    ]

    operations = [
    ]
