# Generated by Django 5.0.14 on 2025-07-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20250724_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_category',
            field=models.CharField(blank=True, help_text='Automatic category assigned by Fabric AI', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, help_text='Fabric AI confidence score (0.0 to 1.0, higher = more confident)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_processing_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when AI processing completed', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_processing_error',
            field=models.TextField(blank=True, help_text='Error message if AI processing failed', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_processing_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when AI processing began', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], help_text='Sentiment analysis result from Fabric AI', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_topics',
            field=models.TextField(blank=True, help_text='JSON array of topics extracted by Fabric AI', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='embedding_json',
            field=models.TextField(blank=True, help_text='JSON representation of embedding vector for compatibility and debugging', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='embedding_vector',
            field=models.BinaryField(blank=True, help_text='Fabric native vector embedding in binary format for optimal performance', max_length='max', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='fabric_ai_processed',
            field=models.BooleanField(default=False, help_text='Indicates whether Fabric AI processing has been completed'),
        ),
        migrations.AddField(
            model_name='question',
            name='fabric_semantic_cluster',
            field=models.CharField(blank=True, help_text='Semantic cluster assigned by Fabric AI for automatic grouping', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='fabric_similarity_indexed',
            field=models.BooleanField(default=False, help_text='Indicates whether the embedding vector is properly indexed in Fabric'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['event', 'created_at'], name='api_questio_event_i_c46fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_starred', 'is_staged'], name='api_questio_is_star_6691c4_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['author', 'created_at'], name='api_questio_author__045469_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['fabric_ai_processed', 'event'], name='api_questio_fabric__fce185_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['fabric_semantic_cluster', 'event'], name='api_questio_fabric__70ce10_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['ai_confidence_score'], name='api_questio_ai_conf_2abb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['ai_sentiment', 'event'], name='api_questio_ai_sent_5acac6_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['ai_category', 'event'], name='api_questio_ai_cate_d98c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['ai_processing_completed_at'], name='api_questio_ai_proc_2fc293_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(('ai_confidence_score__gte', 0.0), ('ai_confidence_score__lte', 1.0)), name='valid_ai_confidence_score'),
        ),
    ]
