# Generated by Django 5.0.14 on 2025-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20250724_1125'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['event', 'created_at'], name='api_questio_event_i_c46fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_starred', 'is_staged'], name='api_questio_is_star_6691c4_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['author', 'created_at'], name='api_questio_author__045469_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['fabric_ai_processed', 'event'], name='api_questio_fabric__fce185_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['fabric_semantic_cluster', 'event'], name='api_questio_fabric__70ce10_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['ai_confidence_score'], name='api_questio_ai_conf_2abb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['ai_sentiment', 'event'], name='api_questio_ai_sent_5acac6_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['ai_category', 'event'], name='api_questio_ai_cate_d98c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['ai_processing_completed_at'], name='api_questio_ai_proc_2fc293_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(('ai_confidence_score__gte', 0.0), ('ai_confidence_score__lte', 1.0)), name='valid_ai_confidence_score'),
        ),
    ]
